@echo off
REM ###########################################################################
REM Script generated by Fortify SCA Scan Wizard (c) 2011-2023 Micro Focus or one of its affiliates
REM Created on 2023/06/28 21:25:43
REM ###########################################################################
REM Generated for the following languages:
REM 	HTML
REM 	Java
REM 	Java Bytecode
REM 	Javascript
REM 	XML
REM ###########################################################################
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM FPR - the name of analysis result file
REM BUILDID - the SCA build id
REM ARGFILE - the name of the argument file that's extracted and passed to SCA
REM BYTECODE_ARGFILE - the name of the argument file for Java Bytecode translation that's extracted and passed to SCA
REM MEMORY - the memory settings for SCA
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="e:\fpo\Fortifyfpouat_may29.fpr"
set BUILDID="fpouat_may29"
set ARGFILE="Fortifyfpouat_may29.bat.args"
set BYTECODE_ARGFILE="Fortifyfpouat_may29.bat.bytecode.args"
set MEMORY=-Xmx14463M -Xms400M -Xss24M 
set LAUNCHERSWITCHES=""
set OLDFILENUMBER=Fortifyfpouat_may29.bat.fileno
set FILENOMAXDIFF=10
set ENABLE_BYTECODE=false

set PROJECTROOT0="E:\FPO\fpouat_may29"
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >%ARGFILE%
echo. >%BYTECODE_ARGFILE%
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM BYTECODE_ARGS" %SCAScriptFile%' ) DO (
   set ENABLE_BYTECODE=true
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~18! >> %BYTECODE_ARGFILE%
)
ENDLOCAL && set ENABLE_BYTECODE=%ENABLE_BYTECODE%

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL% NEQ 0  (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ENABLE_BYTECODE%==true (
echo Translating Java bytecode files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%BYTECODE_ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -scan -f %FPR%
IF %ERRORLEVEL% NEQ 0  (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jboss-logging-3.3.2.Final.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jaxws-api-2.3.1.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-core-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-xml-3.0.4.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\classes;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\hibernate-core-5.3.7.Final.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\mimepull-1.9.10.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-jcl-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\thymeleaf-extras-java8time-3.0.2.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-ws-core-3.0.4.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-data-jpa-2.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-properties-migrator-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-aop-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-configuration-metadata-2.1.1.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-expression-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jasypt-1.9.3.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jackson-databind-2.9.7.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\javassist-3.23.1-GA.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-oxm-5.1.3.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\asm-5.0.4.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\javax.activation-api-1.2.0.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-aspects-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\classmate-1.4.0.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-devtools-2.1.1.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-web-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jackson-datatype-jsr310-2.9.7.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\FastInfoset-1.2.15.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jaxb-api-2.3.1.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\HikariCP-3.2.0.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jaxb-impl-2.3.0.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-tx-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\commons-io-2.5.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\bcprov-jdk14-1.38.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-beans-5.1.3.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\hibernate-validator-6.0.13.Final.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-validation-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-session-core-2.1.2.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-webmvc-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jaxb-runtime-2.3.1.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-session-jdbc-2.1.2.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\dom4j-2.1.1.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-web-services-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\javax.mail-1.6.2.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jul-to-slf4j-1.7.25.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\tomcat-embed-core-9.0.13.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jasypt-spring-boot-starter-3.0.3.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jackson-module-parameter-names-2.9.7.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-logging-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-tomcat-2.1.1.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jasypt-spring-boot-3.0.3.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\log4j-api-2.11.1.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\thymeleaf-3.0.11.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\antlr-2.7.7.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\javax.transaction-api-1.3.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\commons-collections4-4.4.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-aop-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-json-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\tomcat-embed-el-9.0.13.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jackson-core-2.9.7.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\juniversalchardet-2.3.0.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\thymeleaf-spring5-3.0.11.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\unbescape-1.1.6.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\istack-commons-runtime-3.0.7.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\txw2-2.3.1.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\bcmail-jdk14-1.38.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\json-smart-2.3.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\logback-core-1.2.3.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\accessors-smart-1.2.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jackson-annotations-2.9.0.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jackson-datatype-jdk8-2.9.7.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-data-jpa-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\bctsp-jdk14-1.38.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\hibernate-commons-annotations-5.0.4.Final.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\activation-1.1.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\stax-ex-1.8.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\aspectjweaver-1.9.2.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\javax.annotation-api-1.3.2.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\log4j-1.2.17.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\saaj-impl-1.5.0.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-jdbc-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\slf4j-api-1.7.25.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\byte-buddy-1.9.5.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\json-20180130.jar;PROJECTROOT0_MARKER\target\classes"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\javax.xml.soap-api-1.4.0.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\javax.persistence-api-2.2.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-orm-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\log4j-to-slf4j-2.11.1.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\openpdf-1.3.8.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\json-path-2.4.0.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jandex-2.0.5.Final.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-thymeleaf-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-data-commons-2.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\itextpdf-5.0.6.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\snakeyaml-1.23.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-jdbc-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\attoparser-2.0.5.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\logback-classic-1.2.3.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\ojdbc7-12.1.0.2.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\wsdl4j-1.6.3.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\gson-2.8.5.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-web-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-autoconfigure-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\java-uuid-generator-3.1.4.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-context-5.1.3.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\validation-api-2.0.1.Final.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\jaxb-core-2.3.0.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\spring-boot-starter-2.1.1.RELEASE.jar;PROJECTROOT0_MARKER\target\fpo-1.0-SNAPSHOT\WEB-INF\lib\tomcat-embed-websocket-9.0.13.jar"
REM ARGS "-source"
REM ARGS "1.8"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\**\*.jar"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\**\*.class"
REM ARGS "PROJECTROOT0_MARKER"
